### ISSUE TITLE
change phpstan config

### ISSUE THREAD

**Issue by mimmi20** [mimmi20/monolog-factory#320]
```yaml
parameters:
  level: ...

  parallel:
    maximumNumberOfProcesses: 10
    processTimeout: 200.0

  paths:
...

  excludePaths:
    analyse:
...

  scanFiles:
    - %currentWorkingDirectory%/vendor/autoload.php

  checkAlwaysTrueCheckTypeFunctionCall: true
  checkAlwaysTrueInstanceof: true
  checkAlwaysTrueStrictComparison: true
  checkBenevolentUnionTypes: true
  checkDynamicProperties: true
  checkExplicitMixedMissingReturn: true
  checkFunctionNameCase: true
  checkGenericClassInNonGenericObjectType: false
  checkImplicitMixed: true
  checkInternalClassCaseSensitivity: true
  checkMissingCallableSignature: true
  checkMissingIterableValueType: true
  checkTooWideReturnTypesInProtectedAndPublicMethods: true
  checkUninitializedProperties: true
  inferPrivatePropertyTypeFromConstructor: false
  polluteScopeWithAlwaysIterableForeach: false
  polluteScopeWithLoopInitialAssignments: false
//  reportAlwaysTrueInLastCondition: true
  reportMaybesInMethodSignatures: true
  reportMaybesInPropertyPhpDocTypes: true
  reportStaticMethodSignatures: true
//  reportWrongPhpDocTypeInVarTag: true
  treatPhpDocTypesAsCertain: false

  tipsOfTheDay: false

  exceptions:
    implicitThrows: false
    checkedExceptionRegexes:
      - '#Exception#'
      - '#Throwable#'
    check:
      missingCheckedExceptionInThrows: true
      tooWideThrowType: true

  ignoreErrors:
...
```
